config/routes.rb
Rails.application.routes.draw do
  
  root to:"homes#top"
  devise_for :users
  resources :books
  get 'homes/about' => 'homes#about',as:'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user, optional: true
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about, :public_action]
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

   def index
    @books = Book.all
    @book = Book.new
   end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    flash[:notice] = "Book was successfully created."
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @books = Book.all
    @book = Book.find(params[:id])
  end

  def update
    book=Book.find(params[:id])
    if book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(book.id)
    else
      @book=Book.find(params[:id])
      @book.update(book_params)
      render :edit
    end
  end

  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private
  def book_params
   params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
      <% end %>

    </ul>
  </div>
   <% end %>

<h1>Editing Book</h1>

<%= form_with model: @book do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>
<<%= link_to "Show", book_path(@book.id) %>
<%= link_to "back", "/books" %>

app/views/books/index.html.erb
<table>
  <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
  </thead>
  <%= form_with model:@book, local:true do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Body</h5>
  <%= f.text_area :body %>
  <br><%= f.submit "Create Book" %></br>
  <% end %>
 
  <% @books.each do |book| %>
   <body>
     <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to"Show","/books/#{book.id}"%></td>
      <td><%= link_to"Edit","/books/#{book.id}/edit" %></td>
      <td><%= link_to"Destroy","/books/#{book.id}",method: :delete,"data-confirm"=>"Are you sure?" %>
      </td>
    </tr>
    
    <% end %>
   </body>
</table>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>


<b>title:</b>
<p><%= @book.title %></p>

<b>Body:</b>
<p><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "back", "/books" %>

app/views/homes/about.html.erb
<script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>

<h1>Welcime to <i class="fa-solid fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>

<h1>welcome to <i class="fa-solid fa-book"></i>Bookers!!</h1>
<p>in <i class="fa-solid fa-book"></i><b>Bookers,</b></p>

<p>you can share and exechange your opinions, inpressions,and emotions</p>

<p>about various books!</p>


      <p>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-btn btn-info" %>
      </p>
     <p>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-btn btn-success" %>
      </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      Books
    <% if user_signed_in? %>
      <span>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa-solid fa-right-from-bracket"></i>Log out
        <% end %>
      </span>
    <% else %>
      <span>
        <%= link_to root_path do %>
        <i class="fa-solid fa-house"></i>home
        <% end %>
      </span>
      <span>
        <%= link_to about_path do %>
        <i class="fa-solid fa-link-horizontal"></i>>About
        <% end %>
      </span>
      <span>
        <%= link_to new_user_registration_path do %>
        <<i class="fa-regular fa-user-plus"></i>Sing up
        <% end %>
      </span>
      <span>
        <%= link_to  new_user_session_path do %>
        <i class="fa-solid fa-right-to-bracket"></i>Log in
        <% end %>
      </span>

    <% end %>
  </header>
    <%= yield %>
    <footer>
     <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>